### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by anton-kosenko-git** [anton-kosenko-git/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by go-it-bro** [comment]
<h2>Résumé</h2>
<p>&mdash; I am perhaps the most mysterious character in modern history, who created in the 21st century a new religion mixed of 18th century US Wild West and 80s US Wall Street around the whole WWWorld.</p>

**Comment by anton-kosenko-git** [comment]
Good job!
