### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by anton-kosenko-git** [anton-kosenko-git/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by odyn-v-poli** [comment]
<h3>Experience</h3>
<ul class="timeline">
   <li>
      <p><small>2017</small></p>
      <p> Became 45th president of the United States</p>
   </li>
   <li>
      <p><small>2016</small></p>
      <p>Won election race with 77 votes more than Clinton, yippe-kee-yay!</p>
   </li>
   <li>
      <p><small>2015</small></p>
      <p>Became the most important Republican nominating for presidential election run</p>
   </li>
   <li>
      <p><small>2009</small></p>
      <p>Became the most important Republican nominating for presidential election run</p>
   </li>

**Comment by odyn-v-poli** [comment]
<small>1968</small>
Began my career at my 

<small>1971</small>
Was promoted

<small>1980</small>
Started developing

<small>1985</small>
I bought the Mar-a-Lago

<small>1987</small>
Registered as a Republican

<small>1988</small>
Acquired the Plaza Hotel in Manhattan for $407 million

**Comment by go-it-bro** [comment]
<h1 class="name">Satoshi Nakamoto</h>
<div class="job">Bitcoin Godfather</div>
<div class="contacts">
   <li>
      <a href="https://www.facebook.com/groups/740934306101200" rel="author" class="facebook">
         <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M448 56.7v398.5c0 13.7-11.1 24.7-24.7H309.1V306.5h58.218.7-67.6h-67v-43.2c0-19.6 5.4.-32.9 33.5-32.9h35.8v-60.5c-6.2-.8-27.4-2.7-52.2-2.7-51.6 0-87 31.5-87 89.4v49.9h-58.4v67.6h58.4V480H24.7C11.1 480 0 468.9 0 455.3V56.7C0 43.1 11.1 32 24.7 32h398.5c13.7 0 24.8 11.1 24.8 24.7z"/></svg>
         <span>SatoshiNakamoto</span>
      </a>
   </li>

**Comment by anton-kosenko-git** [comment]
It would be cool to create social media accounts too. But it is really out of scope
