### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by anton-kosenko-git** [anton-kosenko-git/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by go-it-bro** [comment]
<h3>Personal life</h3>
<ul class="timeline">
   <li>
      <p><small>2017</small></p>
      <p>Underwent gender reassignment surgery</p>
   </li>
   <li>
      <p><small>2014</small></p>
      <p>Underwent an operation to change appearance</p>
   </li>
   <li>
      <p><small>2013</small></p>
      <p>Deleted all social media accounts</p>
   </li>
   <li>
      <p><small>2008</small></p>
      <p>Published one White paper for fun</p>
   </li>
   <li>
      <p><small>before 2007</small></p>
      <p>Leave an ordinary geek life</p>
   </li>

**Comment by go-it-bro** [comment]
<h3>Experience</h3>
<ul class="timeline">
<li>
<p><small>1981</small></p>
<p>Assembled my first personal computer</p>
</li>
<li>
<p><small>1996</small></p>
<p>Сreated a company that specialized in software for news companies</p>
</li>
<li>
<p><small>2002</small></p>
<p>Вecame interested in space technology</p>
</li>
<li>
<p><small>2007</small></p>
<p>Start  thinking about retirement</p>
</li>

**Comment by anton-kosenko-git** [comment]
Not bad! Thank you
