### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by anton-kosenko-git** [anton-kosenko-git/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by go-it-bro** [comment]
<section>
   <h3>Languge</h3>
   <p class="tags small"><span class="language" lang="c++">&#x1f1fa;&#x1f1f8; C++ - UNDOUBTEDLY</span>
   <p class="tags small"><span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span>
   <p class="tags small"><span class="language" lang="jpn">&#x1f1fa;&#x1f1f8; JAPANESE - possible</span>
</section>

**Comment by go-it-bro** [comment]
<section>
   <h3>Skills</h3>
   <p class="tags small">CODE CREATE INSPIRE CHANGE THE RULES INSPIRE BLOW BUBBLES&#x1f603;
</section>

**Comment by go-it-bro** [comment]
<section>
   <h3>Likes&#x1f603;</h3>
   <p class="tags small"><a href="https://www.youtube.com/watch?v=-p-PKa2BcLc" rel="external">COLLECT CONSPIRACY THEORY ABOUT MYSELF</a></section>

**Comment by go-it-bro** [comment]
<section>
   <h3>Wants&#x1f97a;</h3>
   <p class="tags small bulleted"><span class="tag">DO NOT GET A CORONA</span><span class="tag"> AND YEE GROW A TREE</span></p></section>

**Comment by anton-kosenko-git** [comment]
So pleasant to work with professionals!
